"""
PocketMind Onboarding Skill

Handles the 7-question onboarding process to learn about the user.
"""

import os
import json
from pathlib import Path

# Onboarding questions - aligned with PocketMind original
ONBOARDING_QUESTIONS = [
    {
        "id": 1,
        "key": "name",
        "question": "What should I call you?",
        "description": "Your preferred name or nickname",
        "input_type": "text"
    },
    {
        "id": 2,
        "key": "goal",
        "question": "What's your main goal for having me?",
        "description": "Productivity, learning, creative writing, personal organization, or just chat?",
        "options": ["Productivity & tasks", "Learning & research", "Creative writing", "Personal organization", "Just curious / general chat"],
        "input_type": "choice"
    },
    {
        "id": 3,
        "key": "schedule",
        "question": "What's your typical schedule?",
        "description": "9-5, shift work, flexible, student, or retired?",
        "options": ["9-5 office worker", "Shift work", "Self-employed / flexible", "Student", "Retired"],
        "input_type": "choice",
        "required": False
    },
    {
        "id": 4,
        "key": "timezone",
        "question": "What timezone are you in?",
        "description": "Your local timezone",
        "options": ["Africa/Johannesburg", "Africa/Cairo", "Europe/London", "Europe/Paris", "America/New_York", "America/Los_Angeles", "Asia/Dubai", "Asia/Singapore", "Asia/Tokyo", "UTC"],
        "input_type": "choice"
    },
    {
        "id": 5,
        "key": "important_dates",
        "question": "Any important dates to remember? (birthdays, anniversaries, deadlines)",
        "description": "Leave blank if none",
        "input_type": "text",
        "required": False
    },
    {
        "id": 6,
        "key": "response_style",
        "question": "How do you prefer I respond?",
        "description": "Brief, detailed, casual, or professional?",
        "options": ["Brief & to the point", "Detailed & thorough", "Casual & friendly", "Professional & formal"],
        "input_type": "choice"
    },
    {
        "id": 7,
        "key": "additional_context",
        "question": "Anything else I should know about you?",
        "description": "Your role, interests, or anything important",
        "input_type": "text",
        "required": False
    }
]

# Session state file
SESSION_FILE = "memory/onboarding_session.json"


def get_profile_path(workspace: str) -> str:
    """Get the path to the user profile file."""
    return os.path.join(workspace, "memory", "user-profile.md")


def get_session_path(workspace: str) -> str:
    """Get the path to the onboarding session file."""
    return os.path.join(workspace, SESSION_FILE)


def profile_exists(workspace: str) -> bool:
    """Check if user profile already exists."""
    profile_path = get_profile_path(workspace)
    return os.path.exists(profile_path) and os.path.getsize(profile_path) > 0


def load_profile(workspace: str) -> dict:
    """Load user profile from markdown file."""
    profile_path = get_profile_path(workspace)
    if not profile_exists(workspace):
        return {}
    
    profile = {}
    try:
        with open(profile_path, 'r') as f:
            content = f.read()
            # Parse markdown frontmatter-like format
            lines = content.split('\n')
            for line in lines:
                if ':' in line and not line.startswith('#'):
                    key, value = line.split(':', 1)
                    profile[key.strip()] = value.strip()
    except Exception as e:
        print(f"Error loading profile: {e}")
    
    return profile


def save_profile(workspace: str, profile: dict) -> None:
    """Save user profile to markdown file."""
    profile_path = get_profile_path(workspace)
    os.makedirs(os.path.dirname(profile_path), exist_ok=True)
    
    with open(profile_path, 'w') as f:
        f.write("# User Profile\n\n")
        f.write("Generated by PocketMind Onboarding\n\n")
        for key, value in profile.items():
            f.write(f"- **{key}**: {value}\n")


def load_session(workspace: str) -> dict:
    """Load ongoing onboarding session."""
    session_path = get_session_path(workspace)
    if not os.path.exists(session_path):
        return {"current_question": 0, "answers": {}}
    
    try:
        with open(session_path, 'r') as f:
            return json.load(f)
    except:
        return {"current_question": 0, "answers": {}}


def save_session(workspace: str, session: dict) -> None:
    """Save onboarding session state."""
    session_path = get_session_path(workspace)
    os.makedirs(os.path.dirname(session_path), exist_ok=True)
    
    with open(session_path, 'w') as f:
        json.dump(session, f)


def clear_session(workspace: str) -> None:
    """Clear onboarding session after completion."""
    session_path = get_session_path(workspace)
    if os.path.exists(session_path):
        os.remove(session_path)


def start_onboarding() -> str:
    """Start the onboarding process."""
    return """# Welcome to PocketMind! 🧠

I'm your personal AI memory assistant. I'd love to get to know you better!

Let me ask you a few questions to personalize your experience.

---

**Question 1 of 7**

What should I call you? (Your name or nickname)

*(You can answer all questions at once if you prefer!)*"""


def process_answer(workspace: str, answer: str, session: dict = None) -> dict:
    """Process a user's answer during onboarding."""
    if session is None:
        session = load_session(workspace)
    
    current_q = session.get("current_question", 0)
    
    if current_q == 0 and not answer.strip():
        # Just starting
        return {
            "type": "question",
            "question": ONBOARDING_QUESTIONS[0]["question"],
            "question_num": 1,
            "total": len(ONBOARDING_QUESTIONS)
        }
    
    # Save the answer
    if current_q > 0 and current_q <= len(ONBOARDING_QUESTIONS):
        key = ONBOARDING_QUESTIONS[current_q - 1]["key"]
        session["answers"][key] = answer.strip()
    
    # Move to next question
    current_q += 1
    session["current_question"] = current_q
    
    if current_q > len(ONBOARDING_QUESTIONS):
        # Onboarding complete - save profile
        profile = session["answers"]
        save_profile(workspace, profile)
        clear_session(workspace)
        
        return {
            "type": "complete",
            "message": f"""# Welcome aboard, {profile.get('name', 'friend')}! 🎉

I've saved your profile. Here's what I learned about you:

- **Name**: {profile.get('name', 'Not specified')}
- **Primary Goal**: {profile.get('primary_goal', 'Not specified')}
- **Tasks**: {profile.get('tasks', 'Not specified')}
- **Communication Style**: {profile.get('communication_style', 'Not specified')}
- **Timezone**: {profile.get('timezone', 'Not specified')}
- **Preferences**: {profile.get('preferences', 'None')}
- **Background**: {profile.get('background', 'Not specified')}

You can update your profile anytime by saying "update my profile" or editing `memory/user-profile.md`.

How can I help you today?"""
        }
    
    # Save session and ask next question
    save_session(workspace, session)
    
    q = ONBOARDING_QUESTIONS[current_q - 1]
    
    return {
        "type": "question",
        "question": q["question"],
        "question_num": current_q,
        "total": len(ONBOARDING_QUESTIONS),
        "description": q["description"]
    }


def handle_onboarding(workspace: str, message: str) -> str:
    """Main handler for onboarding flow."""
    message = message.strip().lower()
    
    # Check if user wants to start onboarding
    start_phrases = [
        "onboard", "get to know me", "remember me", 
        "setup profile", "initialize", "new user"
    ]
    
    # Check if profile exists
    if profile_exists(workspace):
        profile = load_profile(workspace)
        name = profile.get("name", "friend")
        return f"I already know you, {name}! Your profile is saved. Say 'update my profile' if you'd like to make changes."
    
    # Load or start session
    session = load_session(workspace)
    
    if session.get("current_question", 0) == 0:
        # Starting fresh
        if any(phrase in message for phrase in start_phrases):
            return start_onboarding()
        else:
            # Trigger onboarding on first message
            return start_onboarding()
    
    # Process answer
    result = process_answer(workspace, message, session)
    
    if result["type"] == "complete":
        return result["message"]
    
    # Return next question
    q_num = result["question_num"]
    total = result["total"]
    
    return f"""**Question {q_num} of {total}**

{result['question']}

{result.get('description', '')}"""


# Nanobot skill integration
# This function is called by Nanobot when the skill is triggered
def execute(workspace: str, context: dict) -> str:
    """Execute the PocketMind onboarding skill."""
    message = context.get("message", "")
    return handle_onboarding(workspace, message)
