#!/bin/bash
# Project-Phase-Worker - Runs every 30 minutes
# Picks next available task from PROJECTS_PLAN.md
# Logs progress to memory/YYYY-MM-DD.md

set -e

WORKSPACE="/root/.openclaw/workspace"
PLAN_FILE="$WORKSPACE/PROJECTS_PLAN.md"
MEMORY_DIR="$WORKSPACE/memory"
TODAY=$(date +%Y-%m-%d)
LOG_FILE="$MEMORY_DIR/${TODAY}.md"

# Ensure memory dir exists
mkdir -p "$MEMORY_DIR"

# Get current hour and minute for logging
TIMESTAMP=$(date +"%H:%M")

# Create log entry if not exists
if [ ! -f "$LOG_FILE" ]; then
    echo "# WolfPack Empire - Daily Log

## $TODAY

*"Generated by Project-Phase-Worker"*

---
" > "$LOG_FILE"
fi

echo "=== Project-Phase-Worker: $TIMESTAMP ===" >> "$LOG_FILE"
echo "" >> "$LOG_FILE"

# Check if there's work to do based on task markers
# Priority: PocketPal > IC > Social Media Agent

WORK_DONE=false

# Function to log and execute a task
execute_task() {
    local task_id=$1
    local task_name=$2
    local task_script=$3
    
    echo "**$task_id:** $task_name - IN PROGRESS" >> "$LOG_FILE"
    echo "Running: $task_script" >> "$LOG_FILE"
    echo "" >> "$LOG_FILE"
    
    # Execute the task script if it exists
    if [ -f "$WORKSPACE/$task_script" ]; then
        cd "$WORKSPACE"
        if bash "$WORKSPACE/$task_script" >> "$LOG_FILE" 2>&1; then
            echo "✅ **$task_id:** $task_name - COMPLETE" >> "$LOG_FILE"
        else
            echo "❌ **$task_id:** $task_name - FAILED" >> "$LOG_FILE"
        fi
    else
        echo "⚠️  **$task_id:** Script not found ($task_script)" >> "$LOG_FILE"
    fi
    
    echo "" >> "$LOG_FILE"
    WORK_DONE=true
}

# Check PocketPal tasks (highest priority - all available)
if [ -f "$WORKSPACE/scripts/pocketpal-status.json" ]; then
    CURRENT_PP=$(cat "$WORKSPACE/scripts/pocketpal-status.json" | grep -o '"current":[0-9]*' | cut -d: -f2)
else
    CURRENT_PP=0
fi

case $CURRENT_PP in
    0)
        execute_task "PP-01" "Consolidate PocketPal repos" "scripts/consolidate-pocketpal.sh"
        echo '{"current":1}' > "$WORKSPACE/scripts/pocketpal-status.json"
        ;;
    1)
        execute_task "PP-02" "Test on local machine" "scripts/test-pocketpal-local.sh"
        echo '{"current":2}' > "$WORKSPACE/scripts/pocketpal-status.json"
        ;;
    2)
        execute_task "PP-03" "Phone edition deployment" "scripts/deploy-pocketpal-phone.sh"
        echo '{"current":3}' > "$WORKSPACE/scripts/pocketpal-status.json"
        ;;
    3)
        execute_task "PP-04" "AgentMesh integration" "scripts/integrate-agentmesh.sh"
        echo '{"current":4}' > "$WORKSPACE/scripts/pocketpal-status.json"
        ;;
    4)
        execute_task "PP-05" "Nanobot/Picoclaw optimization" "scripts/optimize-nanobot.sh"
        echo '{"current":5}' > "$WORKSPACE/scripts/pocketpal-status.json"
        ;;
    *)
        # PocketPal complete, check IC
        if [ -f "$WORKSPACE/scripts/ic-status.json" ]; then
            CURRENT_IC=$(cat "$WORKSPACE/scripts/ic-status.json" | grep -o '"current":[0-9]*' | cut -d: -f2)
        else
            CURRENT_IC=0
        fi
        
        if [ "$CURRENT_IC" -eq 0 ]; then
            execute_task "IC-01" "Set up Google Workspace" "scripts/setup-google-workspace.sh"
            echo '{"current":1}' > "$WORKSPACE/scripts/ic-status.json"
        else
            # Check Social Media Agent
            if [ -f "$WORKSPACE/scripts/sma-status.json" ]; then
                CURRENT_SMA=$(cat "$WORKSPACE/scripts/sma-status.json" | grep -o '"current":[0-9]*' | cut -d: -f2)
            else
                CURRENT_SMA=2  # Start at phase 3 (0-indexed = 2)
            fi
            
            case $CURRENT_SMA in
                2)
                    execute_task "SMA-01" "Content scheduling system" "scripts/build-content-scheduler.sh"
                    echo '{"current":3}' > "$WORKSPACE/scripts/sma-status.json"
                    ;;
                3)
                    execute_task "SMA-02" "Analytics & reporting" "scripts/setup-analytics.sh"
                    echo '{"current":4}' > "$WORKSPACE/scripts/sma-status.json"
                    ;;
                *)
                    echo "⏸️  **$TIMESTAMP:** All non-blocked tasks complete. Waiting for E-man to unblock other phases." >> "$LOG_FILE"
                    echo "" >> "$LOG_FILE"
                    WORK_DONE=true
                    ;;
            esac
        fi
        ;;
esac

if [ "$WORK_DONE" = false ]; then
    echo "⏸️  **$TIMESTAMP:** No tasks to execute at this time." >> "$LOG_FILE"
    echo "" >> "$LOG_FILE"
fi

# Update memory file timestamp
echo "*Updated: $(date +"%Y-%m-%d %H:%M:%S")*" >> "$LOG_FILE"
echo "---" >> "$LOG_FILE"
echo "" >> "$LOG_FILE"

echo "Worker completed at $(date)"
